-- Series settlement policy pack (expanded Φ2)

ALTER TABLE "document_series"
  ADD COLUMN IF NOT EXISTS "allowOverpayment" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "maxTenderLines" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "allowCreditNoteOffset" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowWriteOff" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "writeOffMaxAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "settlementTolerance" DECIMAL(14,2) NOT NULL DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS "allowCashChange" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowGiftCardTender" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowLoyaltyTender" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "requireExternalRef" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "settlementValueDateMode" TEXT NOT NULL DEFAULT 'PAYMENT_DATE',
  ADD COLUMN IF NOT EXISTS "autoPostSettlementJournal" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowVoidSettlement" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowBankMatch" BOOLEAN NOT NULL DEFAULT true;
