-- Expand EntityModule enum for Entity Views / Script Hooks / custom fields
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'SUPPLIERS';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDERS';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'DELIVERY_NOTES';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'CRM_LEADS';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'EMPLOYEES';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'LOYALTY';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'SITES';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRIES';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'MARKETPLACE_CHANNELS';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'PAYMENT_METHODS';
ALTER TYPE "EntityModule" ADD VALUE IF NOT EXISTS 'DOCUMENT_SERIES';

ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "employees" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "crm_leads" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "marketplace_channels" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "loyalty_accounts" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
ALTER TABLE "journal_entries" ADD COLUMN IF NOT EXISTS "customFields" JSONB;
