-- AlterEnum
ALTER TYPE "DocumentKind" ADD VALUE 'SALES_QUOTE';
ALTER TYPE "DocumentKind" ADD VALUE 'RETAIL_RECEIPT';
ALTER TYPE "DocumentKind" ADD VALUE 'PURCHASE_ORDER';
ALTER TYPE "DocumentKind" ADD VALUE 'PURCHASE_INVOICE';
ALTER TYPE "DocumentKind" ADD VALUE 'PURCHASE_CREDIT';
ALTER TYPE "DocumentKind" ADD VALUE 'SUPPLIER_PAYMENT';
ALTER TYPE "DocumentKind" ADD VALUE 'GOODS_RECEIPT';
ALTER TYPE "DocumentKind" ADD VALUE 'STOCK_TRANSFER';
ALTER TYPE "DocumentKind" ADD VALUE 'STOCK_RECEIPT';
ALTER TYPE "DocumentKind" ADD VALUE 'STOCK_ISSUE';
ALTER TYPE "DocumentKind" ADD VALUE 'CANCELLATION';
