import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

async function main() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });

  const tenant = await prisma.tenant.findUnique({ where: { slug: "akropolis" } });
  if (!tenant) throw new Error("Run npm run db:seed first");

  const hq = await prisma.site.upsert({
    where: { tenantId_code: { tenantId: tenant.id, code: "HQ" } },
    update: { name: "Κεντρικά Αθήνα", kind: "BRANCH", isActive: true },
    create: {
      tenantId: tenant.id,
      code: "HQ",
      name: "Κεντρικά Αθήνα",
      kind: "BRANCH",
    },
  });

  const till = await prisma.site.upsert({
    where: { tenantId_code: { tenantId: tenant.id, code: "TILL-01" } },
    update: {
      name: "Ταμείο 1",
      kind: "TILL",
      parentId: hq.id,
      isActive: true,
    },
    create: {
      tenantId: tenant.id,
      code: "TILL-01",
      name: "Ταμείο 1",
      kind: "TILL",
      parentId: hq.id,
    },
  });

  const year = new Date().getFullYear();

  const seriesDefs = [
    {
      code: "ΠΑΡ",
      name: "Παραγγελίες πώλησης",
      kind: "SALES_ORDER" as const,
      prefix: "ΠΑΡ-{YYYY}-",
      nextNumber: 22,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "NONE" as const,
      allowPartial: true,
      myDataEnabled: false,
      isDefault: true,
      glDebitAccount: null as string | null,
      glCreditAccount: null as string | null,
      glVatAccount: null as string | null,
      myDataInvoiceType: null as string | null,
    },
    {
      code: "ΤΙΜ",
      name: "Τιμολόγια πώλησης",
      kind: "SALES_INVOICE" as const,
      prefix: "ΤΙΜ-{YYYY}-",
      nextNumber: 1490,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "DEBIT" as const,
      affectsInventory: "OUT" as const,
      allowPartial: true,
      myDataEnabled: true,
      myDataInvoiceType: "1.1",
      isDefault: true,
      glDebitAccount: "30.00.00",
      glCreditAccount: "70.00.00",
      glVatAccount: "54.00.00",
    },
    {
      code: "ΤΙΜ-T1",
      name: "Τιμολόγια ταμείου 1",
      kind: "SALES_INVOICE" as const,
      prefix: "Τ1-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: till.id,
      affectsCustomer: "DEBIT" as const,
      affectsInventory: "OUT" as const,
      allowPartial: false,
      myDataEnabled: true,
      myDataInvoiceType: "1.1",
      isDefault: false,
      glDebitAccount: "30.00.00",
      glCreditAccount: "70.00.00",
      glVatAccount: "54.00.00",
    },
    {
      code: "ΠΙΣ",
      name: "Πιστωτικά τιμολόγια",
      kind: "SALES_CREDIT" as const,
      prefix: "ΠΙΣ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "CREDIT" as const,
      affectsInventory: "IN" as const,
      allowPartial: false,
      myDataEnabled: true,
      myDataInvoiceType: "5.1",
      isDefault: true,
      glDebitAccount: "70.00.00",
      glCreditAccount: "30.00.00",
      glVatAccount: "54.00.00",
    },
    {
      code: "ΕΙΣ",
      name: "Εισπράξεις πελατών",
      kind: "CUSTOMER_RECEIPT" as const,
      prefix: "ΕΙΣ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: till.id,
      affectsCustomer: "CREDIT" as const,
      affectsInventory: "NONE" as const,
      allowPartial: true,
      myDataEnabled: true,
      myDataInvoiceType: "8.1",
      isDefault: true,
      glDebitAccount: "38.00.00",
      glCreditAccount: "30.00.00",
      glVatAccount: null,
    },
    {
      code: "ΔΑ",
      name: "Δελτία αποστολής",
      kind: "DELIVERY_NOTE" as const,
      prefix: "ΔΑ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "OUT" as const,
      allowPartial: true,
      myDataEnabled: true,
      myDataInvoiceType: "9.3",
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΠΡΟΣ",
      name: "Προσφορές",
      kind: "SALES_QUOTE" as const,
      prefix: "ΠΡΟΣ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "NONE" as const,
      allowPartial: false,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΑΠΥ",
      name: "Αποδείξεις λιανικής",
      kind: "RETAIL_RECEIPT" as const,
      prefix: "ΑΠΥ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: till.id,
      affectsCustomer: "DEBIT" as const,
      affectsInventory: "OUT" as const,
      allowPartial: false,
      myDataEnabled: true,
      myDataInvoiceType: "6.1",
      isDefault: true,
      glDebitAccount: "30.00.00",
      glCreditAccount: "70.00.00",
      glVatAccount: "54.00.00",
    },
    {
      code: "ΠΑΓ",
      name: "Παραγγελίες αγοράς",
      kind: "PURCHASE_ORDER" as const,
      prefix: "ΠΑΓ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "NONE" as const,
      allowPartial: true,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΔΠ",
      name: "Δελτία παραλαβής",
      kind: "GOODS_RECEIPT" as const,
      prefix: "ΔΠ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "IN" as const,
      allowPartial: true,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΤΑΓ",
      name: "Τιμολόγια αγοράς",
      kind: "PURCHASE_INVOICE" as const,
      prefix: "ΤΑΓ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "CREDIT" as const,
      affectsInventory: "IN" as const,
      allowPartial: false,
      myDataEnabled: true,
      myDataInvoiceType: "1.1",
      isDefault: true,
      glDebitAccount: "20.00.00",
      glCreditAccount: "50.00.00",
      glVatAccount: "54.00.00",
    },
    {
      code: "ΠΑΓ-ΠΙΣ",
      name: "Πιστωτικά αγοράς",
      kind: "PURCHASE_CREDIT" as const,
      prefix: "ΠΑΓΠ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "DEBIT" as const,
      affectsInventory: "OUT" as const,
      allowPartial: false,
      myDataEnabled: true,
      myDataInvoiceType: "5.1",
      isDefault: true,
      glDebitAccount: "50.00.00",
      glCreditAccount: "20.00.00",
      glVatAccount: "54.00.00",
    },
    {
      code: "ΠΛΗΡ",
      name: "Πληρωμές προμηθευτών",
      kind: "SUPPLIER_PAYMENT" as const,
      prefix: "ΠΛΗΡ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: till.id,
      affectsCustomer: "DEBIT" as const,
      affectsInventory: "NONE" as const,
      allowPartial: true,
      myDataEnabled: true,
      myDataInvoiceType: "8.2",
      isDefault: true,
      glDebitAccount: "50.00.00",
      glCreditAccount: "38.00.00",
      glVatAccount: null,
    },
    {
      code: "ΕΝΔ",
      name: "Ενδοδιακινήσεις",
      kind: "STOCK_TRANSFER" as const,
      prefix: "ΕΝΔ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "OUT" as const,
      allowPartial: true,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΕΙΣΑΓ",
      name: "Εισαγωγές αποθήκης",
      kind: "STOCK_RECEIPT" as const,
      prefix: "ΕΙΣΑΓ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "IN" as const,
      allowPartial: false,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΕΞΑΓ",
      name: "Εξαγωγές αποθήκης",
      kind: "STOCK_ISSUE" as const,
      prefix: "ΕΞΑΓ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "OUT" as const,
      allowPartial: false,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
    {
      code: "ΑΚΥΡ",
      name: "Ακυρωτικά",
      kind: "CANCELLATION" as const,
      prefix: "ΑΚΥΡ-{YYYY}-",
      nextNumber: 1,
      lastYear: year,
      siteId: hq.id,
      affectsCustomer: "NONE" as const,
      affectsInventory: "NONE" as const,
      allowPartial: false,
      myDataEnabled: false,
      myDataInvoiceType: null,
      isDefault: true,
      glDebitAccount: null,
      glCreditAccount: null,
      glVatAccount: null,
    },
  ];

  for (const def of seriesDefs) {
    await prisma.documentSeries.upsert({
      where: { tenantId_code: { tenantId: tenant.id, code: def.code } },
      update: {
        // Do not touch nextNumber / lastYear — preserve live counters
        name: def.name,
        kind: def.kind,
        prefix: def.prefix,
        siteId: def.siteId,
        affectsCustomer: def.affectsCustomer,
        affectsInventory: def.affectsInventory,
        allowPartial: def.allowPartial,
        myDataEnabled: def.myDataEnabled,
        myDataInvoiceType: def.myDataInvoiceType,
        myDataVatCategory: "1",
        glDebitAccount: def.glDebitAccount,
        glCreditAccount: def.glCreditAccount,
        glVatAccount: def.glVatAccount,
        isDefault: def.isDefault,
        isActive: true,
        resetPolicy: "YEARLY",
        padLength: 5,
      },
      create: {
        tenantId: tenant.id,
        code: def.code,
        name: def.name,
        kind: def.kind,
        prefix: def.prefix,
        nextNumber: def.nextNumber,
        lastYear: def.lastYear,
        siteId: def.siteId,
        affectsCustomer: def.affectsCustomer,
        affectsInventory: def.affectsInventory,
        allowPartial: def.allowPartial,
        myDataEnabled: def.myDataEnabled,
        myDataInvoiceType: def.myDataInvoiceType,
        myDataVatCategory: "1",
        glDebitAccount: def.glDebitAccount,
        glCreditAccount: def.glCreditAccount,
        glVatAccount: def.glVatAccount,
        isDefault: def.isDefault,
        isActive: true,
        resetPolicy: "YEARLY",
        padLength: 5,
      },
    });
  }

  console.log(`Seeded sites + ${seriesDefs.length} document series`);
  await prisma.$disconnect();
  await pool.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
